version: '3.7'
services:
  nginx:
    build: ./docker/nginx
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
      - "447:447"
    environment:
      - VIRTUAL_HOST=site.local
      - VIRTUAL_PORT=80
    restart: always
    depends_on:
      - php
    networks:
      - network
  php:
    build: ./docker/php
    restart: always
    volumes:
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./app:/var/www/html
    networks:
      - network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx-proxy:
    image: nginx-proxy/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - network
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - network
    ports:
      - "3307:3306"

networks:
  network:
    external: true

