version: '2'

services:
#  mariadb:
#    image: docker.io/bitnami/mariadb:10.6
#    environment:
#      # ALLOW_EMPTY_PASSWORD is recommended only for development.
#      - ALLOW_EMPTY_PASSWORD=yes
#      - MARIADB_USER=admin
#      - MARIADB_DATABASE=pikoba
  myapp:
    image: docker.io/bitnami/laravel:9
    privileged: true
    ports:
      - '80:8000'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=test
      - DB_DATABASE=pikoba
    volumes:
      - './app:/app'
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
